version: "3.8"

services:
  user-service:
    build: ./user-service
    volumes:
      - ./user-service/data:/app/data
    environment:
      - FLASK_ENV=production
      - USER_SERVICE_URL=http://user-service:5000  # variable para URL interna del user-service
    networks:
      - backend
    ports:
      - "5001:5000"    # expone puerto 5001 en host, 5000 en contenedor

  task-service:
    build: ./task-service
    volumes:
      - ./task-service/data:/app/data
    environment:
      - USER_SERVICE_URL=http://task-service:5000  # variable para URL interna del task-service
      - FLASK_ENV=production
    networks:
      - backend
    ports:
      - "5002:5000"    # expone puerto 5002 en host, 5000 en contenedor

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data/nginx/data:/data
      - ./data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - backend

networks:
  backend:
    driver: bridge
